name: ðŸŽ¨ Design/UX Feedback
description: Suggest improvements to the user interface or experience
title: "[Design]: "
labels: ["enhancement", "design"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for your design feedback!
        
        We appreciate suggestions to improve the user experience.
        
        > âš ï¸ **Important**: This tracker is for **UI/UX suggestions only**. 
        > We cannot accept issues about AI-generated responses, answer accuracy, or AI behavior.

  - type: checkboxes
    id: not-ai-issue
    attributes:
      label: Confirmation
      description: Please confirm this is not an AI response issue
      options:
        - label: This feedback is about the user interface or experience, NOT about AI-generated answers
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of Improvement
      description: Which part of the application does this relate to?
      options:
        - Chat Interface
        - Navigation/Header
        - Mobile Experience
        - Dark/Light Mode
        - Typography/Fonts
        - Colors/Theming
        - Animations/Transitions
        - Accessibility
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe the current design or UX
      placeholder: How does it currently work/look?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: Describe your proposed change
      placeholder: What would you like to see instead?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why This Would Help
      description: Explain how this change would improve the user experience
      placeholder: This would improve the experience because...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, sketches, or examples from other apps, share them here
      placeholder: Drag and drop images here, or paste links to examples...

  - type: dropdown
    id: device
    attributes:
      label: Primary Device
      description: Which device type is this most relevant for?
      options:
        - Desktop
        - Mobile
        - Tablet
        - All Devices
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: Add any other details here...
